services:
  api:
    build:
      context: .
      dockerfile: TicketFlow.Api/Dockerfile
    restart: on-failure
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=${MYSQL_DATABASE};Uid=${MYSQL_USER};Pwd=${MYSQL_ROOT_PASSWORD};
      - RedisConnection=redis,abortConnect=false
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__UserName=${RABBITMQ_DEFAULT_USER:-guest}
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS:-guest}
      - Seq__Url=http://seq
    depends_on:
      - mysql
      - rabbitmq
      - redis
      - seq

  # 2. Banco de Dados
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT:-3307}:3306"

  # 3. Mensageria
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - "5672:5672"   # Protocolo
      - "15672:15672" # Painel Visual

  # 4. Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 5. Logs
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_ADMIN_PASSWORD:-admin}
    ports:
      - "5341:80"