services:
  api:
    build:
      context: .
      dockerfile: TicketFlow.Api/Dockerfile
    restart: on-failure
    ports:
      - "5000:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=TicketFlow;Uid=root;Pwd=senhaForte123;
      - RedisConnection=redis,abortConnect=false
      - RabbitMQ__Host=rabbitmq
      - Seq__Url=http://seq
    depends_on:
      - mysql
      - rabbitmq
      - redis
      - seq

  # 2. Banco de Dados
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: senhaForte123
      MYSQL_DATABASE: TicketFlow
    ports:
      - "3307:3306"

  # 3. Mensageria
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Protocolo
      - "15672:15672" # Painel Visual

  # 4. Cache
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # 5. Logs
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:80"